### PR TITLE
Switch to `https` URLs everywhere.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @mikelambert @RyanZim

### CODE REVIEW

**Comment by XhmikosR** [comment]
So it seems phantomjs has issues on Travis while it works fine on AppVeyor. Unfortunately we can't pass any options ourselves to phantomjs since it's called by chai-resemble. Yet another reason to drop chai-resemble...

**Comment by mikelambert** [comment]
I'm confused. Do you know why it's failing on Travis? What options would you want to pass to fix it?

I presume chai-resemble does work on travis (https://travis-ci.org/giakki/chai-resemble/jobs/109139849), which is why I'm not sure it's "evidence of another reason to drop chai-resemble" ?

**Comment by XhmikosR** [comment]
It doesn't work with https. That enough reason to me... anyway there was a
flag to make phantom ignore ask errors. That might fix the issue. But again
we don't own chai-resemble and it's clearly something unmaintained

**Comment by mikelambert** [comment]
Ah, got it.

So where is the https problem here? With chai-resemble or with phantomjs? chai-resemble is another package adjacent to this one, and presumably easy to submit changes to. To fix the https error, or to pass a new flag to phantomjs, or whatever.

I have trouble believing phantomjs has fundamental issues with https though.

**Comment by XhmikosR** [comment]
But chai-resemble is unmaintained too :/ We'd need to use our fork/package. That is why I say it would be much better if we moved away from chai-resemble completely.

**Comment by mikelambert** [comment]
Ahh okay.

I thought the objection for chai-resemble was based on the dependency tree and phantomjs, which I don't personally care about for a dev-only dependency. Likewise, an unmaintained dependency isn't a bad thing either...oftentimes projects just don't need updates. But in this case, it seems there is a bug with chai-resemble and https, and so *now* the unmaintained nature of it can become an issue. :)

So, now it becomes a tradeoff: Do you want to add tests that reference https urls? If so, are you willing to replace the entire chai-resemble tree to get there? I still think the easiest solution is to just ask giakki (via email) for commit privileges to chai-resemble (similar to what we did with uncss) to make what would presumably be a one-line fix.

But I'll defer to you, as you seem much more motivated to work on and solve these issues.

**Comment by zaigham** [comment]
I think PhantomJS 1.x has problems with SNI based https.

**Comment by RyanZim** [comment]
I'm not clear on what problems this PR attempts to fix?

**Comment by XhmikosR** [comment]
@RyanZim @mikelambert: can you guys pass the

**Pull request closed without merging**
