### PR TITLE
Add option ignoreModifiers, to ignore classes or other modifiers

### PR DESCRIPTION
**Pull request by twiss**
The selector is only ignored if it does match without the given modifier.

### CODE REVIEW

**Comment by RyanZim** [comment]
@twiss I'm not sure what this PR is trying to accomplish. Can you give an example of how you would use this feature?

**Comment by twiss** [comment]
Let's say you have a class, `.hidden`, which is added in javascript to two elements, one of which exists on the current page and one of which does not.

With `ignore: [/\.hidden/]`, uncss does:

````diff
  .exists { color: blue }
  .exists.hidden { display: none }
  
- .doesnt-exist { color: orange }
  .doesnt-exist.hidden { display: none }
````

With `ignoreModifiers: ['.hidden']`, uncss does:

````diff
  .exists { color: blue }
  .exists.hidden { display: none }
  
- .doesnt-exist { color: orange }
- .doesnt-exist.hidden { display: none }
````

In other words, it ignores the selector only if it *does* match *without* the "modifer". This is what you want in most cases, and in my project it ended up making a significant difference in CSS size (although I don't remember the details since this is almost a year ago.)

**Comment by RyanZim** [comment]
OK, I see what you mean.

@XhmikosR @mikelambert Thoughts?

**Comment by XhmikosR** [comment]
I personally don't get the purpose of this patch. You can match specific selectors already.

**Comment by twiss** [comment]
Maybe a real life example helps. Take a look at this file: https://github.com/codexa/firetext/blob/3a08345/style/bb/input_areas.css#L293-337. It is part of a CSS library called "building blocks". We don't need all of the css in that library, so uncss helps. Most of the files in that library (and our own css too) have a section for rtl support, which starts with `[dir="rtl"]`. The old way to ignore those would be `ignore: [/\[dir="rtl"\]/]`, which also ignores rtl support for parts of the library which we don't use. `ignoreModifiers: '[dir="rtl"]'` does what we want.

**Comment by RyanZim** [comment]
This PR is so stale, resolving merge conflicts would probably be harder than reimplementing this, so closing.

**Pull request closed without merging**
