### PR TITLE
#265: Replace PhantomJS with jsdom

### PR DESCRIPTION
**Pull request by vseventer**
See discussion at #265 for background.

### CODE REVIEW

**Comment by RyanZim** [comment]
@vseventer Can you force-push to re-trigger the travis build?

**Comment by RyanZim** [comment]
@giakki @XhmikosR @mikelambert Thoughts on this?

**Comment by RyanZim** [comment]
Current status of this: https://github.com/giakki/uncss/issues/265#issuecomment-270266120

**Comment by RyanZim** [comment]
You can test this branch with this package: https://www.npmjs.com/package/uncss-jsdom.

**Comment by gkatsanos** [comment]
jsdom saved me from 2h of trying to find why phantomjs wasnt doing the job. please merge it :)

**Comment by davidtheclark** [comment]
@RyanZim I tried out this branch and had a problem. JSDom did not find an asset (a JS file) that PhantomJS was loading without trouble. I wonder if there's something wrong with the asset lookup.

**Comment by mikelambert** [comment]
What is an "asset" specifically, and how are you loading it? Is it a basic `<script>` tag? Anything interesting in how it's specified or used? Any repro case you can link to?

**Comment by davidtheclark** [comment]
Here is a simple test repo that reproduces the problem I was seeing: https://github.com/davidtheclark/uncss-jsdom-test

With the PhantomJS version, this test works. With uncss-jsdom, I see this error:

```
Error: Could not load script: "file:///test.js"
    at /Users/davidclark/Downloads/uncss-jsdom-test/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:44:23
    at Object.check (/Users/davidclark/Downloads/uncss-jsdom-test/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:88:11)
    at ReadStream.<anonymous> (/Users/davidclark/Downloads/uncss-jsdom-test/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:107:12)
    at ReadStream.wrappedEnqueued (/Users/davidclark/Downloads/uncss-jsdom-test/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at fs.js:1678:12
    at FSReqWrap.oncomplete (fs.js:82:15) { [Error: ENOENT: no such file or directory, open '/test.js'] errno: -2, code: 'ENOENT', syscall: 'open', path: '/test.js' }
```

@mikelambert sorry if the terminology wasn't clear. By "asset" I meant a file that is referenced with a `<script>` or `<link>` or something similar. This case is a basic `<script>` tag.

**Comment by RyanZim** [comment]
@davidtheclark Will investigate.

**Comment by RyanZim** [comment]
@davidtheclark The issue is the leading `/` in the asset path. Since assets are loaded via `file://`, a leading `/` bases the path off of the OS root directory.

The PhantomJS uncss had couldn't load these assets either, however, it failed silently, jsdom correctly reports the error.

You need to use `htmlroot`

**Comment by davidtheclark** [comment]
@RyanZim I tried it with `htmlroot` and got the same error. Do you not get that error with teh test repo?

**Comment by vseventer** [comment]
uncss allows `/css/main.css`, so there is no reason why `/js/main.js` shouldn't be supported also. This could be fixed by having `htmlroot` (or, more precise, [utility.parsePath](https://github.com/RyanZim/uncss/blob/uncss-jsdom/src/utility.js#L53)) apply to stylesheets and scripts (currently, it only applies to stylesheets).

Don't think this is a particular issue with jsdom, especially if PhantomJS ignores the JS file anyway.

**Comment by davidtheclark** [comment]
@vseventer want me to open a separate issue?

**Comment by davidtheclark** [comment]
@vseventer @RyanZim Thanks for chiming in! I opened up #287 for this issue. I guess it still seems to me that this problem needs to be addressed before the JSDom implementation merges, or else the JSDom implementation should deliver a warning but not throw an error when it encounters root-relative paths. If the behavior is not changed, then a very common and widespread practice will break uncss, right?

**Comment by RyanZim** [comment]
> If the behavior is not changed, then a very common and widespread practice will break uncss, right?

Yes and No. PhantomJS would quietly output without processing the JS; jsdom fails hard (which is better IMO). Either way, this should be addressed (see https://github.com/giakki/uncss/issues/287#issuecomment-281682625).

 To be clear, switching to jsdom was always intended to be a breaking change.

**Comment by davidtheclark** [comment]
@RyanZim: I agree that it's important to bring to the user's attention the fact that their JS is not loading; but a hard failure would mean that we suddenly can't use uncss with our valid HTML that worked before, right? For my example, as one example, I do not care whether the JS loads, would even prefer to be able to tell uncss *not* to try to load it.

Just wanted to make sure I was being clear about my concern. Thanks for your work on the transition!

**Comment by ArmorDarks** [comment]
Nice work!

Any estimations when it will be released?

**Comment by ArmorDarks** [comment]
We've tested this branch on our relatively large project, which used PhantomJS-based uncss before.

Everything seems to work perfectly, except few things:

1. Already mentioned issue with relative paths to js files

   Most annoying that so far it is unclear how to bypass this error.

   Our file:

   ``` html
   <script src='/assets/scripts/main.min.js'></script>
   ```

   Results in error

   ```
   Error: Could not load script: "file:///J:/assets/scripts/main.min.js"
     at J:\Work\FASenergo\github\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:44:23
     at Object.check (J:\Work\FASenergo\github\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:88:11)
     at Object.check (J:\Work\FASenergo\github\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:91:23)
     at J:\Work\FASenergo\github\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:107:12
     at wrappedEnqueued (J:\Work\FASenergo\github\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:255:16)  at Request.request [as _callback] (J:\Work\FASenergo\github\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:203:9)
     at Request.self.callback (J:\Work\FASenergo\github\node_modules\jsdom\node_modules\request\request.js:186:22)
     at emitTwo (events.js:106:13)
     at Request.emit (events.js:192:7)
     at Request.<anonymous> (J:\Work\FASenergo\github\node_modules\jsdom\node_modules\request\request.js:1081:10)  at emitOne (events.js:96:13)
     at Request.emit (events.js:189:7)
     at Gunzip.<anonymous> (J:\Work\FASenergo\github\node_modules\jsdom\node_modules\request\request.js:1001:12)
     at Object.onceWrapper (events.js:291:19)
     at emitNone (events.js:91:20)
     at Gunzip.emit (events.js:186:7)
     at endReadableNT (_stream_readable.js:974:12)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
    { Error: ENOENT: no such file or directory, open 'J:\assets\scripts\main.min.js'

     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'J:\\assets\\scripts\\main.min.js' }
   ```

2. If we delete links to js files, everything works fine. However, for some reason this class gets stripped in jsdom version:

   ``` css
   svg:not(:root) { overflow: hidden; }
   ```

   I wonder why? It doesn't render :root properly?

However, there are also few positive things:

1. It consumes two times less memory
2. Turned out that PhantomJS version wrongly stripped those classes:

   ```css
   @media print {
     *,
     *:before,
     *:after,
     *:first-letter, /* this */
     *:first-line /* and this */ { background: transparent !important; ... }
   ```

   In jsdom version they preserved, as expected.

**Comment by RyanZim** [comment]
@ArmorDarks 

1. WIP PR to fix JS issue: https://github.com/vseventer/uncss/pull/2.
1. Hmm... needs investigation. Looks like a bug in jsdom.

**Comment by ArmorDarks** [comment]
Guys, any ETA on this? :)

**Comment by mikelambert** [comment]
@ArmorDarks does this patch work for you? It's a major change to uncss, so I was hoping to get as much testing as we could. (Earlier testing found some issues, which had some patches sent out)

**Comment by ArmorDarks** [comment]
@mikelambert I understand. We definitely need to attract more people explicitely. Not all checking issues regularly. Maybe you have someone to mention to ask for testing? Otherwise it is good practice to release new version of uncss which will echo into console invitation to tests. This might sound slightly invasive, but it's okay.

Here are my results with `uncss-jsdom` 2.0.0:

1. Issue with js files still persists. Each `<script>` declaration throws this error:

   ```
    { Error: ENOENT: no such file or directory, open 'J:\Work\TestProject\github\build\J:\assets\scripts\main.min.js'


     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'J:\\Work\\TestProject\\github\\build\\J:\\assets\\scripts\\main.min.js' }
   Error: Could not load script: "file:///J:/assets/scripts/main.min.js"
     at J:\Work\TestProject\github\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:44:23
     at Object.check (J:\Work\TestProject\github\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:89:11)
     at ReadStream.<anonymous> (J:\Work\TestProject\github\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:108:12)
     at ReadStream.wrappedEnqueued (J:\Work\TestProject\github\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:255:16)
     at emitOne (events.js:96:13)
     at ReadStream.emit (events.js:189:7)
     at fs.js:1863:12
     at FSReqWrap.oncomplete (fs.js:114:15)
   ```

   Note how paths are screwed.

   However, now it doesn't prevent `uncss-jsdom` from actually finishing styles processing.

2. Output of processed CSS is still same as described in https://github.com/giakki/uncss/pull/280#issuecomment-283157456 and in most cases even _mor accurate_.

   Unfortunately, except related to `:root` elements, probably due to mentioned https://github.com/tmpvar/jsdom/issues/1750.

   For us it's completely non-critical. Can't say for others.

3. Everything else seems to work magnificently.

**Comment by RyanZim** [comment]
@davidtheclark @vseventer Looks like we still screwed absolute path handling; see @ArmorDarks comment above.

---

@ArmorDarks As a temporary workaround, you can put `'svg:not(:root)'` in the `ignore` list. Still, this should be fixed.

**Comment by vseventer** [comment]
@ArmorDarks I'm trying to replicate the problem - what is the absolute path to `/assets/scripts/main.min.js`? Did you set the `htmlroot` to `J:\Work\TestProject\github\build`?

**Comment by ArmorDarks** [comment]
@vseventer 

> what is the absolute path to /assets/scripts/main.min.js

Full path is `J:/Work/TestProject/github/build/assets/scripts/main.min.js`

In html declared as `<script src='/assets/scripts/main.min.js'></script>`

During development all files served from `J:/Work/TestProject/github/build/`

> Did you set the htmlroot to J:\Work\TestProject\github\build?

Ouch, I supposed to configure `htmlroot` explicitly somewhere? Where should it be done? I've completely missed it.

I'm still confused, why it's able to read CSS without `htmlroot`, but can't do same thing for JS?

**Comment by RyanZim** [comment]
> Ouch, I supposed to configure htmlroot explicitly somewhere? Where should it be done? I've completely missed it.

It depends on your environment; the same place you'd set `ignore`.

> I'm still confused, why it's able to read CSS without htmlroot, but can't do same thing for JS?

Do you use absolute paths for your CSS?

**Comment by ArmorDarks** [comment]
> It depends on your environment; the same place you'd set ignore.

Ah, I see. Turned out that it was already defined in config with value `build`.

uncss launched from project root with Node, `J:/Work/TestProject/github/`

So, now we need to set `htmlroot` to full path, like `J:/Work/TestProject/github/build/`?

> Do you use absolute paths for your CSS?

Yes, for images, like `url(/assets/images/sprites/sprite.png)`.

However, I do not use CSS imports, everything done through Sass, so `uncss` always receives single large CSS file

**Comment by RyanZim** [comment]
> so uncss always receives single large CSS file

The `htmlroot` option has no impact unless you're only passing your HTML to uncss. If you're passing the css file name directly to uncss, it doesn't use `htmlroot`, except for JS.

> Yes, for images, like url(/assets/images/sprites/sprite.png).

uncss doesn't load them anyhow, so it doesn't matter.

> So, now we need to set htmlroot to full path, like J:/Work/TestProject/github/build/?

Correct

**Comment by ArmorDarks** [comment]
> The htmlroot option has no impact unless you're only passing your HTML to uncss. If you're passing the css file name directly to uncss, it doesn't use htmlroot, except for JS.

I see. That's what exactly I'm doing — passing only HTML files to uncss.

Sorry for confusion. When I said "so uncss always receives single large CSS file" I meant that `<link rel='stylesheet' href='/assets/styles/style.css'>` always pointing to already built huge CSS file.

> Correct

Hm, that's quite strange. Aren't there a way to avoid this, by using `process.cwd()` or something like this internally in `uncss`?

This isn't hard to workaround, but seems to be strange and uncommon for node modules. Usually libraries does not require to provide complete absolute paths and relying on current cwd. If something somewhere needs full path, it always can append cwd internally. Or I'm missing something?

**Comment by RyanZim** [comment]
> If something somewhere needs full path, it always can append cwd internally.

Sorry, my bad; `htmlroot` can be relative to cwd.

**Comment by ArmorDarks** [comment]
> Sorry, my bad; htmlroot can be relative to cwd.

Yeap, tested with full paths — seems to be no difference.

I thought that issue might be related to [Grunt task](https://github.com/addyosmani/grunt-uncss). But I desicted it and simplified to plain example, and it made no difference too.

Here is simplified case:

Grunt task:

```js
const uncss = require('uncss-jsdom')

module.exports = function (grunt) {
  grunt.registerMultiTask('uncss', 'Remove unused CSS', function () {
    const done = this.async()

    uncss('build/index.html', { htmlroot: 'build' }, function () {
      done()
    })
  })
}
```

`/build/index.html`:

```html
<!doctype html>
<html>

  <head>
    <link rel='stylesheet' href='/assets/styles/style.css'>
  </head>

  <body>
    <script src='/assets/scripts/main.js'></script>
  </body>

</html>
```

`build/assets/styles/style.css`:

```css
.test { border: 0 }
```

`build/assets/scripts/main.js`:

```js
console.log('Hi!')
```

You can see full structure in [Kotsu](https://github.com/LotusTM/Kotsu) repository (though, you will need to build it to see `build` directory). In fact, you can install Kotsu, then go into `/node_modules/grunt-uncss/tasks` and change require inside js file to `uncss-jsdom`, and test whole thing with Kotsu to see same error.

Hm, I also peeked into error message again and thought — maybe it's related to OS-specific path normalization? Windows handles paths differently from Linux (uses `\` for paths instead of `/`), and I'm exactly on Windows 10...

**Comment by vseventer** [comment]
@ArmorDarks It might be - I'm using the test files (on Mac) as you described and Hi! gets logged to the console. I will try the same on my Windows machine later today, and see if that makes a difference.

**Comment by ArmorDarks** [comment]
So sad without this PR :(

@vseventer Did you have any time to do test on PC?

**Comment by vseventer** [comment]
@ArmorDarks Sorry, this escaped my attention, I'm on Mac so this is not high priority for me. That said, I'll try and get to it in the next couple of days.

**Comment by mikelambert** [comment]
So this has been sitting around awhile, while I left it unintegrated hoping for more testing (didn't realize it would take so long and lose momentum, sorry!)

AFAIK, these are the only two known issues?
- svg root is broken: https://github.com/tmpvar/jsdom/issues/1750
- possibly broken on windows (didn't really follow all the details)

Is it worth adding a built-in ignore to catch the svg/root issue? I'm not clear on this syntax, to know if a valid uncss ignore regex can be built that catches all these cases? (Then we could ship without breaking clients, and could just remove the built-in ignore when https://github.com/tmpvar/jsdom/issues/1750 gets fixed.)

And assuming it is broken on Windows (and not something unique to @ArmorDarks setup), I would consider that blocking bug (even though I also am only on Mac). @ArmorDarks , do you think you'd have any time to dig into the uncss/jsom code yourself and see where things are going wrong and where a patch might be devised? Otherwise we're just hoping @vseventer can find the time to do more testing... :)

**Comment by ArmorDarks** [comment]
@mikelambert Yeap, this seems to be right

> AFAIK, these are the only two known issues?

So far yes, That's the only ones we were able to find on our codebase. It should cover most part of use cases, but we don't use some part of CSS at all (for instance, deeply nested selectors with high specificity), so I can only hope that it won't break anything on more tricky codebases. But I think we'll never know untill will let it go into the wild, since it seems that not much people finding that PR and even less doing testing.

> Is it worth adding a built-in ignore to catch the svg/root issue? I'm not clear on this syntax, to know if a valid uncss ignore regex can be built that catches all these cases? (Then we could ship without breaking clients, and could just remove the built-in ignore when tmpvar/jsdom#1750 gets fixed.)

👍 

> And assuming it is broken on Windows (and not something unique to @ArmorDarks setup), I would consider that blocking bug (even though I also am only on Mac). @ArmorDarks , do you think you'd have any time to dig into the uncss/jsom code yourself and see where things are going wrong and where a patch might be devised? Otherwise we're just hoping @vseventer can find the time to do more testing... :)

Well, I can try to do something, but I'm not very skilled JavaScript developer. So far I'm pretty much sure that it's related to Windows-specific paths formatting (`\` in paths instead of `/`).

It would be great if @vseventer or someone else on PC would finally test it, so we can be sure that it isn't related to my specific configuration, though, I tried to make build with stripped everything else, to minimize the effect of possible configuration flaws.

**Comment by RyanZim** [comment]
@mikelambert That svg root problem is actually a hack in normalize css for an old version of IE (I think IE9?) You'd never use a selector like that in normal real life. `ignore: ['svg:not(:root)']` might do the job.

Windows does need fixed, but I'm stranded on a Linux box, so can't help there.

**Comment by vseventer** [comment]
I'm able to reproduce the issue on Windows - a quick peek shows that the drive letter in Windows is the issue. (Root-)relative paths will always have the drive letter in front, so prepending the `htmlroot` will cause something like `<htmlroot>/C:/<relative path>`, while on Mac/Unix, we get the correct `<htmlroot>/<relative path>`.

Unfortunately, JSDom does some manipulation on the script `src` before exposing it, preventing me from reading out the actual script src attribute value without drive letter.

I will do some further testing later this week.

**Comment by vseventer** [comment]
@ArmorDarks I added a commit which greatly simplifies the `resourceLoader`. Tests pass in both Mac and Windows, maybe you can give it a go to see if it works for you?

**Comment by ArmorDarks** [comment]
Hi

Thanks for update!

Issue with local js-files finally fixed, thanks!

But there is a couple of other issues:

1. jsdom tries to execute everything on page, including JavaScript. If any JS file fails, obviously, jsdom will report about that issue and may fail. From one side, it is cool, since serves as additional testing tool, but the bad side comes exactly from its good side — testing should be done explicitly whenever developers chooses too, but, instead, uncss will enforce testing of all JS.

   Not sure we can do anything about it, though.

   I guess after merge of this PR we will receive a lot of issues in uncss repository like `ahhh, uncss doesn't work, tons of errors!", since it will unexpectedly shed light on all errors of local and 3rd party scripts, which won't be able properly execute in jsdom...

2. Loading of remote scripts (when you have something like `src='https/... somescript.js') isn't super-reliable and rarely, but fails. Well, nothing can be done about it, I guess

3. There seems to be quite specific issue with scripts, which injects something and relying on window location.

   For instance, here is `<script>` which serves as loader of 3rd-party script (sorry for minification, it is as provided by service)

   ```html
   <script>
     ! function(t) {
       function e() {
         i = document.querySelectorAll(".button-widget-open");
         for (var e = 0; e < i.length; e++) "true" != i[e].getAttribute("init") && (options = JSON.parse(i[e].closest('.' + t).getAttribute("data-settings")), i[e].setAttribute("onclick", "alert('" + options.errorMessage + "(0000)'); return false;"))
       }
   
       function o(t, e, o, n, i, r) {
         var s = document.createElement(t);
         for (var a in e) s.setAttribute(a, e[a]);
         s.readyState ? s.onreadystatechange = o : (s.onload = n, s.onerror = i), r(s)
       }
   
       function n() {
         for (var t = 0; t < i.length; t++) {
           var e = i[t];
           if ("true" != e.getAttribute("init")) {
             options = JSON.parse(e.getAttribute("data-settings"));
             var o = new MangoWidget({
               host: window.location.protocol + '//' + options.host,
               id: options.id,
               elem: e,
               message: options.errorMessage
             });
             o.initWidget(), e.setAttribute("init", "true"), i[t].setAttribute("onclick", "")
           }
         }
       }
   
       host = window.location.protocol + "//widgets.mango-office.ru/";
       var i = document.getElementsByClassName(t);
   
       o("link", {
         rel: "stylesheet",
         type: "text/css",
         href: host + "css/widget-button.css"
       }, function() {}, function() {}, e, function(t) {
         document.documentElement.insertBefore(t, document.documentElement.firstChild)
       }), o("script", {
         type: "text/javascript",
         src: host + "widgets/mango-callback.js"
       }, function() {
         ("complete" == this.readyState || "loaded" == this.readyState) && n()
       }, n, e, function(t) {
         document.documentElement.appendChild(t)
       })
     }("mango-callback");
   </script>
   ```

   And it results in quite specific situation, when jsdom tries to load that resource as a local one:

   

   Obviously, issue comes from `window.location.protocol + '//' + options.host` concatenation. I guess `jsdom` places as location `file` protocol, and it results in error. I wonder, can anything be done about this?

   In this example we able to replace window location with hardcoded protocol, but it isn't always possible when script loaded from 3rd party.

4. jsdom seems to be not handling relative protocols

   ```html
   <script src='//widget.mango-office.ru/js/c-t-w.min.js'></script>
   ```

   Will result in error: 

   

   I guess because jsdom tries to resolve everything to local filesystem...

   Not big deal for us, I think those days relative protocols shouldn't be used anyway, but on some people it might come unexpectedly.

   Also, in some cases you're unable to change relative protocol. For example, when you're fetching script from 3rd party.

4. This line

   ```html
   <script charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ad2ff4a462886ef9b0e6af874ac0d2b927f993be421b25cb2fc8db71efd9a9cb2&amp;width=100%25&amp;height=320&amp;lang=ru_RU&amp;scroll=true"></script>
   ```

   Yielded quite strange error:

   

   It seems related to remote resource, once again, but format of error is quite different. It was unable to parse url properly?

**Comment by vseventer** [comment]
I think we're pushing the limits of jsdom here. Regarding 1 and 2, ideally scripts should be executed within a sandbox, but don't think this is a priority for the jsdom maintainers. Given that jsdom loads the source from disk, yeah, it uses the `file://` protocol, causing issues 3 and 4 you mentioned.

Honestly, the issues you mention should be resolved. Not sure how, though.

**Comment by mikelambert** [comment]
Are 1 and 2 warnings, or failures? Warning about bad loads and missing resources is fine. Erroring-out and dying completely, is not fine. If the latter, can you give an example stacktrace? I feel like page-resource loads should be executed within a try/catch in jsdom, to allow the page to finish loading as best it can...

3 and 4, I don't believe we can do anything about. And I don't believe this is anything "new" about jsdom. Phantomjs loading a file from local disk, would have the same issue, right? (It possibly was too-silent about errors, and maybe the file just went missing when run from PhantomJS)

**Comment by RyanZim** [comment]
> Phantomjs loading a file from local disk, would have the same issue, right? (It possibly was too-silent about errors, and maybe the file just went missing when run from PhantomJS)

I think that's what was happening; haven't verified though.

**Comment by ArmorDarks** [comment]
All errors aren't warning, they are full errors with stack trace, but they do not crash `jsdom`, so uncss indeed can successfully finish. That's great!

However, that's true only if it is impossible to load or execute properly remote script, but not CSS.

For instance, one of 3rd party scripts containing following line:

```js
window.location.protocol + "//widgets.mango-office.ru/css/widget-button.css"
```

or

```js
"//widgets.mango-office.ru/css/widget-button.css"
```

will result in

```
Fatal error: UnCSS: could not open J:\Work\FASenergo\github\build\widgets.mango-office.ru\css\widget-button.css
```

Easy fix is to change relative protocol to static `https`, but. as I said, not all users will have access to 3rd party script content, and this concatenation, unfortunately, is very common (anti) pattern.

Though, I guess, it can be fixed by simply ignoring such specific CSS files with something like `/widgets.mango-office.ru/`.

Also, in general, situation with `window.location.protocol` and relative protocols feels a bit regretful and a lot of users will bash into it, but so far I can't see too what we can do about it.

**Comment by mikelambert** [comment]
So I wouldn't call it an anti-pattern. It certainly sucks for file:// based pages. But for any website (or script library!) that needs to work on both http and https, scheme-relative paths are actually the *correct* solution. But yes, it's an unfortunate consequence how they break with file:// pages. :(

As far as CSS error-breakage you list above, this is actually an UnCSS error, not a jsdom error. See https://github.com/giakki/uncss/blob/master/src/utility.js#L123 . So on the bright side, this error is:
- much easier to fix if we want
- should not be related to the jsom-based implementation, so not a blocking issue for release

Just want to check though, does your hard-breakage error occur even with the original PhantomJS implementation? (It shouldn't)

Looks like the code currently is designed to raise an error when attempting to load a local (relative) file that does not exist. I can see the pros of making local uncss references failures, but also the cons since scheme-relative URLs become local references in a way that I think is difficult for uncss to detect...

**Comment by ArmorDarks** [comment]
> So I wouldn't call it an anti-pattern. It certainly sucks for file:// based pages. But for any website (or script library!) that needs to work on both http and https, scheme-relative paths are actually the correct solution. But yes, it's an unfortunate consequence how they break with file:// pages. :(

I definitely had to avoid mention about "anti" part to avoid this offtopic. Not, it isn't good solution. Whenever you have `https` source, use `https`. There is no harm in using `https` source at `http`-served page, there is only harm if you use `http` on `https`-served one. But if you don't have `https` source, relative protocol won't help anyway. I think conclusions are quite straightforward.

Anyway, it doesn't make any point, since a lot of sites still using it and we have to live with it for now.

> Just want to check though, does your hard-breakage error occur even with the original PhantomJS implementation? (It shouldn't)

PhantomJS version raises identical error:

conemu_2017-06-24_14-44-37

So, in this matter jsdom doesn't bring any breaking changes.

**Comment by RyanZim** [comment]
@mikelambert What else needs done here? (other than fixing merge conflicts)

**Comment by mikelambert** [comment]
Ahhh sorry for the delay.

@ArmorDarks Thanks, good points there, I should have known that. :) 

@RyanZim Nope, don't think anything else is required. Does someone want to fix up the merge conflicts, and then we can try a major-semver release with a few pending changes?

**Comment by RyanZim** [comment]
@vseventer Can you fix merge conflicts? (or should someone else do it)

**Comment by ArmorDarks** [comment]
Just for the note, with `jsdom` `uncss` for some reason also strips this CSS:

```css
::placeholder {
    color: #5a6066;
    font-family: inherit;
    font-size: 16px;
    font-style: inherit
}
```

While browsers-specific placeholders will be left intact:

```css
::-webkit-input-placeholder {
    color: #5a6066;
    font-family: inherit;
    font-size: 16px;
    font-style: inherit
}
:-ms-input-placeholder {
    color: #5a6066;
    font-family: inherit;
    font-size: 16px;
    font-style: inherit
}
```

Though, `jsdom` seems to work with placeholder pseudo-selector.

As of right now, this is easily workaroundable with ignore rule.

**Pull request merged**
