### PR TITLE
Postcss plugin

### PR DESCRIPTION
**Pull request by mikelambert**
This one is a follow-up to https://github.com/giakki/uncss/pull/212, that implements the plugin. I've verified that sourcemaps work correctly in my local testing/usage.

### CODE REVIEW

**Comment by mikelambert** [comment]
Curious, should I be using peerDependencies for the postcss dependency?

**Comment by XhmikosR** [comment]
Wasn't peerDependencies dropped in npm 3?

**Comment by mikelambert** [comment]
Oh, hah, looks like I'm somehow still running npm 2 (I must have installed it ages ago, but really only started actively using npm a couple weeks ago, and must have gotten confused by the warnings I saw regarding peerDependencies).

Also potentially more worrisome, https://github.com/postcss/postcss says postcss doesn't work on 0.10.0 and provides a polyfill workaround. I've tried to set that up, but it still doesn't pass the travis build on 0.10.0. I suspect I'm going to need to install 0.10.0 locally to dig in before it's committable (assuming we want to retain bwcompat to 0.10.0)...but hopefully the rest of the change can be reviewed and stable in the meantime.

**Comment by XhmikosR** [comment]
I'd say it's OK to drop 0.10 support if @giakki agrees too.

**Comment by mikelambert** [comment]
Well I got 0.10 to work, once I fixed my version comparison string.

Though another point of mention, phantom (either our use of it, or the library itself) seems to perform very poorly with concurrency. If you combine CSS before passing to Uncss, things work fine, but if you process multiple files in parallel (as is done in webpack without a choice), execution errors and you get malformed CSS. I've solved this by serializing all Uncss use (and thus Phantom use) across Postcas plugin invocations, but technically the problem still exists with regular Uncss (I ran into this problem when using gulp based setup that ran two tasks that called Uncss in parallel)

So this is fixed for Postcss parallelizatiom in this pull request, but let me know if you want me to serialize it for any/all invocations altogether.

**Comment by XhmikosR** [comment]
@giakki: it might be worth giving @mikelambert push rights.

**Comment by giakki** [comment]
Wowzers! Thanks @mikelambert! I've given you push rights, you can merge this in! :smiley:

**Comment by giakki** [comment]
@XhmikosR I agree, we can safely drop support for 0.10, maybe we can test against 0.12?

**Comment by XhmikosR** [comment]
@giakki: @mikelambert mentions above that he fixed 0.10 support so we should be OK for now.

**Pull request merged**
