### PR TITLE
jsdom: specify `omitJSDOMErrors: true`.

### LINKED ISSUE #322: TypeError with v0.15
So, when running `grunt` in grunt-uncss master repo, after installing `canvas-prebuilt` package I get:

```
C:\Users\xmr\Desktop\grunt-uncss>grunt
Running "clean:tests" (clean) task
>> 1 path cleaned.

Running "copy:dist" (copy) task
Created 3 directories, copied 14 files

Running "uncss:dist" (uncss) task
Error: Could not load script: "file://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"
  at C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:44:23
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:89:11)
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:92:23)
  at C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:108:12
  at wrappedEnqueued (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:255:16)
  at ReadStream.readableStream.on (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:76:7)
  at emitNone (events.js:110:20)
  at ReadStream.emit (events.js:207:7)
  at endReadableNT (_stream_readable.js:1047:12)
  at _combinedTickCallback (internal/process/next_tick.js:102:11)
  at process._tickCallback (internal/process/next_tick.js:161:9)
 Error: Invalid protocol: file:
  at Request.init (C:\Users\xmr\Desktop\grunt-uncss\node_modules\request\request.js:460:31)
  at new Request (C:\Users\xmr\Desktop\grunt-uncss\node_modules\request\request.js:130:8)
  at request (C:\Users\xmr\Desktop\grunt-uncss\node_modules\request\index.js:54:10)
  at Object.exports.download (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:185:15)
  at fetch (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:136:20)
  at Object.exports.load (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:270:11)
  at HTMLScriptElementImpl._attach (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:35:22)
  at HTMLBodyElementImpl._attach (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:294:15)
  at HTMLBodyElementImpl._attach (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:110:11)
  at HTMLHtmlElementImpl._attach (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:294:15)
  at HTMLHtmlElementImpl._attach (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:110:11)
  at DocumentImpl.insertBefore (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:227:22)
  at DocumentImpl.appendChild (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:334:17)
  at DocumentImpl.appendChild (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:400:18)
  at setChild (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\htmltodom.js:288:18)
  at HtmlToDom._parseWithparse5v1 (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\htmltodom.js:90:7)
  at HtmlToDom.appendHtmlToDocument (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\htmltodom.js:47:48)
  at setInnerHTML (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:71:27)
  at DocumentImpl.write (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:453:7)
  at Document.write (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\generated\Document.js:351:27)
  at Object.exports.jsdom (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom.js:144:21)
  at processHTML (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom.js:302:26)
  at resourceLoader.readFile (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom.js:229:11)
  at ReadStream.readableStream.on (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:76:7)
  at emitNone (events.js:110:20)
  at ReadStream.emit (events.js:207:7)
  at endReadableNT (_stream_readable.js:1047:12)
  at _combinedTickCallback (internal/process/next_tick.js:102:11)
  at process._tickCallback (internal/process/next_tick.js:161:9)
```

It seems jsdom can't parse protocol relative files? With phantom-js this worked out of the box.

Now, if I replace jquery to use https I get:

```
C:\Users\xmr\Desktop\grunt-uncss>grunt
Running "clean:tests" (clean) task
>> 1 path cleaned.

Running "copy:dist" (copy) task
Created 3 directories, copied 14 files

Running "uncss:dist" (uncss) task
Error: Uncaught [TypeError: Cannot read property 'firstChild' of null]
  at reportException (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:58:24)
  at processJavaScript (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:130:7)
  at HTMLScriptElementImpl._eval (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:65:7)
  at C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:31:22
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:89:11)
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:92:23)
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:92:23)
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:92:23)
  at C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:108:12
  at wrappedEnqueued (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:255:16)
  at Request.request [as _callback] (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:203:9)
  at Request.self.callback (C:\Users\xmr\Desktop\grunt-uncss\node_modules\request\request.js:188:22)

  at emitTwo (events.js:125:13)
  at Request.emit (events.js:213:7)
  at Request.<anonymous> (C:\Users\xmr\Desktop\grunt-uncss\node_modules\request\request.js:1171:10)
  at emitOne (events.js:115:13)
  at Request.emit (events.js:210:7)
  at Gunzip.<anonymous> (C:\Users\xmr\Desktop\grunt-uncss\node_modules\request\request.js:1091:12)
  at Object.onceWrapper (events.js:314:30)
  at emitNone (events.js:110:20)
  at Gunzip.emit (events.js:207:7)
  at endReadableNT (_stream_readable.js:1047:12)
  at _combinedTickCallback (internal/process/next_tick.js:102:11)
  at process._tickCallback (internal/process/next_tick.js:161:9)
 TypeError: Cannot read property 'firstChild' of null
  at file:///C:/Users/xmr/Desktop/grunt-uncss/tests/app/js/main.js:21:15
  at ContextifyScript.Script.runInContext (vm.js:53:29)
  at Object.runInContext (vm.js:108:6)
  at processJavaScript (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:128:10)
  at HTMLScriptElementImpl._eval (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:65:7)
  at C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:31:22
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:89:11)
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:92:23)
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:92:23)
  at Object.check (C:\Users\xmr\Desktop\grunt-uncss\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:92:23)
```

https://github.com/addyosmani/grunt-uncss/blob/master/tests/app/js/main.js

That part is created on runtime. Shouldn't it parse just fine?

### PR DESCRIPTION
**Pull request by XhmikosR**
See https://github.com/tmpvar/jsdom#virtual-consoles

This fixes #322 for me. So the behavior is like before the jsdom switch.

/CC @mikelambert @RyanZim

### CODE REVIEW

**Comment by XhmikosR** [comment]
Also, with this change protocol-relative URLs seem to work again, or at least don't throw.

**Comment by XhmikosR** [comment]
OK, I believe this is the opposite of what we want. So I'm not sure how to proceed... Note that this really works for me with the updated jsdom.

**Comment by mikelambert** [comment]
I believe JS errors (for whatever reason) will indicate the page is not fully set up, and so it is impossible for uncss to make the traditional guarantees it makes.

It just so happens that phantom was extremely lenient in ways that none of us knew. But I don't think anyone would argue that is a desirable state.

My argument, if someone were complaining to me about this in a bug/issue:
- don't use scheme-relative urls. specify the scheme
- possibly implement (if it's not already implemented) a "base path against which to resolve host-relative-urls" feature, so one could continue to use host-relative urls
- do not run uncss on raw html files. If you want to load host-relative content, you need to run on a host. set up a server for the duration of the uncss run, and run it against that

However, if you want to make an uncss flag that causes it to "ignore errors and potentially generate malformed pages at your own peril" escape hatch, then that would be fine with me too.

**Comment by RyanZim** [comment]
Agree :100: with @mikelambert. 

> if you want to make an uncss flag that causes it to "ignore errors and potentially generate malformed pages at your own peril" escape hatch, then that would be fine with me too.

I think this is a good idea.

**Comment by XhmikosR** [comment]
All right, sounds a good idea. I'll try to implement it when I have some time.

**Pull request closed without merging**
