### PR TITLE
Adding user agent string as an available option

### PR DESCRIPTION
**Pull request by bbeesley**
We have adaptive css, ie you get different styles based on whether you're on desktop/tablet/mobile/whatever, so I was hoping you could pull this guy to let me configure the user agent that jsdom uses.

### CODE REVIEW

**Comment by RyanZim** [comment]
Looks pretty good, can you add an entry in the docs below the command line usage block?

I guess changing the default user-agent won't break existing usage?

**Comment by RyanZim** [comment]
Just noting that this is based against the `develop` branch (which is correct).

**Comment by bbeesley** [comment]
Sure, I'll update the docs in the morning. I can't see it causing any issues changing the default user agent string, but I can change it to whatever the default jsdom one is if you prefer (or just not pass the option if it's unset)

**Comment by RyanZim** [comment]
> I can't see it causing any issues changing the default user agent string, but I can change it to whatever the default jsdom one is if you prefer (or just not pass the option if it's unset)

I don't really forsee issues either, but I wanted the other collaborators opinions on it.

**Comment by XhmikosR** [comment]
I don't get why there are the other patches in this PR?

**Comment by bbeesley** [comment]
Not sure what you mean by that @XhmikosR 
I branched from develop, and the PR is against develop. Looks like a bunch of stuff was merged last night so I've had to rebase and push again, but there's nothing in the diff here that isn't related to this feature.
@RyanZim I've updated the commit with a description of the option on the README. I haven't touched the default string, lmk if you want me to change it.

**Comment by XhmikosR** [comment]
Well now it's OK after the rebase.

**Comment by RyanZim** [comment]
Yeah, sorry; I forgot about this PR and rebased `develop` onto `master`. My bad.

**Pull request merged**
