### PR TITLE
Add support for comma-seperated animation property

### LINKED ISSUE #188: Animation keyframes that are referenced in a chain are removed
It appears that animation keyframes that are only ever referenced as part of a chain are not recognized as being 'used'. Example is from Effeckt.css:
```css
.effeckt-list[data-effeckt-type='pop-in'] .new-item {
  max-height: 0;
  opacity: 0;
  transform: translateX(-300px);
  animation: openSpace 500ms ease forwards, moveIn 750ms 500ms ease forwards; }

@keyframes openSpace {
  to {
    max-height: 50px; } }

@keyframes moveIn { /* this was removed without explicit ignore */
  to {
    opacity: 1;
    transform: translateX(0); } }
```

Specifying `/moveIn/` in ignore works to keep the keyframes in.

### PR DESCRIPTION
**Pull request by RyanZim**
Fixes #188.

### CODE REVIEW

**Comment by RyanZim** [comment]
The tests pass locally, coveralls had spotty uptime when travis was running so the coveralls task failed.

**Comment by RyanZim** [comment]
@XhmikosR Perhaps you could trigger a rerun of the Travis build?

**Comment by XhmikosR** [comment]
Done. You can just force push your branch by changing the commit date and it should trigger a new build in the future.

**Comment by RyanZim** [comment]
@XhmikosR Not sure what this error message means:
```
Running "mochacov:coveralls" (mochacov) task

Warning: Unable to fetch base options: Command failed: git cat-file -p b150c401ef56af463882ac719d8b77bfa0eea802

fatal: Not a valid object name b150c401ef56af463882ac719d8b77bfa0eea802

 Use --force to continue.

Aborted due to warnings.
```

**Pull request closed without merging**
