### PR TITLE
BREAKING: Upgrade to postcss 6

### LINKED ISSUE #305: Upgrade to postcss 6
Postcss 6.0 “Marquis Orias” is out; uncss should upgrade.

Release notes: https://github.com/postcss/postcss/releases/tag/6.0.0

This should be semver-major for our postcss users.

I can try to get this done when I get a chance, but if someone else wants to go ahead, that's fine.

### PR DESCRIPTION
**Pull request by RyanZim**
Resolves #305 

This needs to be released as semver-major

Attn: @mikelambert

### CODE REVIEW

**Comment by mikelambert** [comment]
I assume JSDom will also be a breaking change, maybe it's worth putting both of them in together for a new major semver release? (And then patch-fixing-forward any other remaining JSDom issues that might be found over the course of folks installing it?)

**Comment by RyanZim** [comment]
@mikelambert I'm all for it! :shipit:

If there's any patch-fixing that needs done as a result of this, I'll try to help as I'm able.

**Comment by mikelambert** [comment]
And why does this need to be released as semver-major? Does it break any the uncss API at all in a way clients would notice? Or is that just a safety precaution?

Only thing I can see is a dropping of node 0.12 support, which I think might be sufficient reason in case anyone's still using that version?

**Comment by RyanZim** [comment]
@mikelambert If you're using uncss as a postcss plugin, using plugins with differing major versions of postcss can cause issues.

**Pull request merged**
