### PR TITLE
Tell PhantomJS where to look for files

### PR DESCRIPTION
**Pull request by giakki**
I'm trying to use phantom.openPage to see if we can tell phantom where to look for JS files.

### CODE REVIEW

**Comment by giakki** [comment]
@addyosmani thanks for the input, I'll switch to 1.6.0 then.
The performance hit is not due to css, that was introduced with c5c4152, but I have a solution for that.

**Comment by XhmikosR** [comment]
I confirm it now works fine on Windows with my repo. It seems to be still slower than 0.8.1 though.

This branch:

```
Execution Time (2015-01-02 12:20:27 UTC)
jekyll:site     6.1s  █████████ 17%
uncss:dist     27.4s  █████████████████████████████████████ 78%
uglify:minify  438ms  █ 1%
htmlmin:dist   640ms  █ 2%
Total 35.1s
```

Using 0.8.1:
```
Execution Time (2015-01-02 12:23:14 UTC)
jekyll:site     5.1s  ███████████████████████ 49%
uncss:dist      3.8s  ██████████████████ 36%
uglify:minify  422ms  ██ 4%
usemin:html    156ms  █ 1%
htmlmin:dist   625ms  ███ 6%
Total 10.5s
```

So it's 3 times slower...

**Comment by ben-eb** [comment]
@XhmikosR Awesome! So are we ready to fix #111 yet? :wink:

**Comment by giakki** [comment]
Cheers!
I think the performance can be improved a bit more, but I'll merge this, so we can get this out of the way.

**Comment by XhmikosR** [comment]
@ben-eb: yes, I think the next release should be good to use. Only issue left is the slowdown.

**Comment by ben-eb** [comment]
@XhmikosR :beers:

**Pull request merged**
