### PR TITLE
Add banner option to disable default uncss banner.

### PR DESCRIPTION
**Pull request by simi**
Hello!

This is my naive implementation of optional banner in result.

For now, I'm not sure how to handle missing banner in `parseErrorMessage` and if that's actually needed.

What do you think about this feature?

### CODE REVIEW

**Comment by RyanZim** [comment]
Not flatly opposed to this, but curious what the concrete use-case for this is.

**Comment by simi** [comment]
I'm motivated by some changes I did recently for https://uncss-online.com/.

**Comment by RyanZim** [comment]
BTW, I'd be in favor of adding https://uncss-online.com/ to the README here.

**Comment by simi** [comment]
I was thinking about that also.

**Comment by simi** [comment]
I'm also missing more README.md changes. Will update soon.

**Comment by XhmikosR** [comment]
Can this be rebased against master and add any missing stuff?

Also CC @mikelambert for thoughts.

**Comment by simi** [comment]
@XhmikosR done.

**Pull request merged**
