### PR TITLE
Update phridge and is-absolute-url, and fix ESLint error.

### PR DESCRIPTION
**Pull request by mikelambert**
- phridge migrated off when.js promises onto native promises, so we need to wrap them in a couple places to support .spread(). This was guided by tests (basically, finding the entry points that go through getHTML), and I don't believe there should be any leakage of this change outside the UnCSS API.
- is-absolute-url started treating '//somedomain.com/file.html' as not-absolute, which broke our tests. But arguably, the test was broken...if we pass a protocol-less URL in to UnCSS, there's no existing protocol that we should be accessing the protocol-relative URL against. (ie, should it be accessed over http or https? It's undefined...) So I deleted this test.

### CODE REVIEW

**Comment by XhmikosR** [comment]
So, we just need a new test for protocol URLs?

/CC @giakki

**Comment by mikelambert** [comment]
My belief is that the existing test was flawed...we should not be supporting protocol relative URLs in the toplevel API at all, and so do not need a new test. If someone gives us a URL "//www.google.com/app.css", there is no way that we can fetch it, since we don't know through what port or protocol to request it.

**Comment by XhmikosR** [comment]
@mikelambert: but things will work for protocol relative URLs, like before, or not?

**Comment by mikelambert** [comment]
Sorry, I don't really understand your question in the context of my
explanation. What is this "before" support that you want to keep working?
Is it a fear of losing functionality we theoretically once had
(functionally that I don't believe anyone in their right mind could have
actually used, but was just an artifact of an overzealous test case). Or is
there a concrete use case you believe we need to keep supporting, and if so
can you describe how someone would be using those protocol urls in html
urls without any protocol to be relative against?

2016年2月19日(金) 19:04 XhmikosR <notifications@github.com>:

**Comment by XhmikosR** [comment]
I might have misunderstood this issue. Anyway, feel free to merge.

**Comment by XhmikosR** [comment]
@mikelambert: any chance that we switch to phantomjs-prebuilt?

**Comment by XhmikosR** [comment]
Hmm, scratch that, it's actually phridge that references it.

**Pull request merged**
