### PR TITLE
Let vendor-specific pseudo-classes be considered for deletion.

### PR DESCRIPTION
**Pull request by mikelambert**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mikelambert: is there any noticeable slowdown from this change?

**Comment by mikelambert** [comment]
I didn't run any benchmarks, but I wouldn't expect (and didn't see) any obvious slowdown. This regex will only apply if the pseudo-class begins with a ":", and will abort the match quickly otherwise. So yes, it might be marginally slower, but only in proportion to the the number of vendor-specific prefixes you are using (and therefore potentially removing).

(Though as a side note...why are we special-casing any of tthese pseudo-classes at all? Can't we just make a blanket assumption that all pseudo-classes are only relevant to the page if their parent selector is relevant? Could simplify this further by doing a /::?[a-z0-9-]+/ regex, if so.

**Comment by XhmikosR** [comment]
I'd say we revisit that in a future PR.

**Comment by XhmikosR** [comment]
@giakki: any objections to this?

**Pull request merged**
